name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run eslint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: out

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: Deploy to Vercel
        uses: vercel/vercel-action@v2
        with:
          project: ${{ secrets.VERCEL_PROJECT_ID }}
          token: ${{ secrets.VERCEL_TOKEN }}
          # Comment out or uncomment the following line based on your deployment strategy
          #  -  production: Default Vercel production environment
          #  - preview: For preview deployments
          #  - staging: For staging deployments
          # You can define additional environment variables for deployment
          #  -  VERCEL_ENV=development
          # For more options, see https://github.com/vercel/vercel-action
          # ... your Vercel deployment options